DELIMITER |
CREATE PROCEDURE avg_time()
BEGIN
DECLARE @StartDate DATE = select min(DATE_STATIONNEMENT_E) from STATIONNEMENT;
DECLARE @EndDate DATE = select max(DATE_STATIONNEMENT_E) from STATIONNEMENT;

SELECT NOM_PARKING, AVG(PLACE_DISPO)
    WHILE (@StartDate <= @EndDate)
    select NOM_PARKING, CONCAT(@StartDate,$h),P.CAPACITE - COUNT(*) AS "PLACE_DISPO" from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
        where (S.DATE_STATIONNEMENT_E <= CONCAT(@StartDate,$h) AND (S.DATE_STATIONNEMENT_S >= CONCAT(@StartDate,$h) OR S.DATE_STATIONNEMENT_S is null))
        group by NOM_PARKING;
    set @StartDate = DATEADD(day, 1, @StartDate);
group by NOM_PARKING;
END |
DELIMITER ;

CALL avg_time();



SELECT NUMERO_IMMATRICULATION, NOM_PARKING, AVG(DUREE_STAT) as "durée moyenne voit/par"
from(select NUMERO_IMMATRICULATION, NOM_PARKING,TIMESTAMPDIFF(HOUR,S.DATE_STATIONNEMENT_E,S.DATE_STATIONNEMENT_S) AS DUREE_STAT
    from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING) AS T
group by NUMERO_IMMATRICULATION, NOM_PARKING;

SELECT NUMERO_IMMATRICULATION, AVG(COUT_STAT) AS "cout moyenne de stationnement"
from (select NUMERO_IMMATRICULATION,NOM_PARKING, SUM(P.TARIF * TIMESTAMPDIFF(HOUR,S.DATE_STATIONNEMENT_E,S.DATE_STATIONNEMENT_S)) AS "COUT_STAT" 
        from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
        group by NUMERO_IMMATRICULATION,NOM_PARKING
        ) AS T
group by NUMERO_IMMATRICULATION;

SELECT S.ID_PARKING, NOM_PARKING, COUNT(*)
from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
group by S.ID_PARKING, NOM_PARKING
order by COUNT(*) desc;

/*we need to add select par COMMUNE*/
SELECT NOM_PARKING, NOM_DE_COMMUNE, SUM(COUT_STAT) AS "cout de stationnement"
from (select NUMERO_IMMATRICULATION,NOM_PARKING, NOM_DE_COMMUNE, SUM(P.TARIF * TIMESTAMPDIFF(HOUR,S.DATE_STATIONNEMENT_E,S.DATE_STATIONNEMENT_S)) AS "COUT_STAT" 
        from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING inner join COMMUNE C on C.CODE_POSTALE = P.CODE_POSTALE
        group by NUMERO_IMMATRICULATION,NOM_PARKING
        ) AS T
group by NOM_PARKING, NOM_DE_COMMUNE
having NOM_DE_COMMUNE = "Pessac"
order by SUM(COUT_STAT) desc;

SELECT C.CODE_POSTALE, COUNT(*)
from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING inner join COMMUNE C on C.CODE_POSTALE = P.CODE_POSTALE
where S.DATE_STATIONNEMENT_E between '2022-11-23 16:14:0' and '2022-11-30 16:14:0'
group by C.CODE_POSTALE
order by COUNT(*) desc;