select NOM_PARKING, PLACE_DISPO_BAR
from (select NOM_PARKING, COUNT(*) AS "PLACE_DISPO_BAR" from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
     where (S.DATE_STATIONNEMENT_E <= $date AND (S.DATE_STATIONNEMENT_S >= $date OR S.DATE_STATIONNEMENT_S is null))
     group by NOM_PARKING) AS T;

select NUMERO_IMMATRICULATION, NOM_PARKING, AVG(DUREE_STAT) as "durée moyenne voit/par"
from(select NUMERO_IMMATRICULATION, NOM_PARKING, DATEDIFF(S.DATE_STATIONNEMENT_S,S.DATE_STATIONNEMENT_E) * 24 AS "DUREE_STAT"
    from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING) AS T
group by NUMERO_IMMATRICULATION, NOM_PARKING;

select NUMERO_IMMATRICULATION, AVG(COUT_STAT) AS "cout moyenne de stationnement"
from (select NUMERO_IMMATRICULATION,NOM_PARKING, SUM(P.TARIF * DATEDIFF(HOUR,S.DATE_STATIONNEMENT_S,S.DATE_STATIONNEMENT_E) * 24) AS "COUT_STAT" 
        from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
        group by NUMERO_IMMATRICULATION,NOM_PARKING
        ) AS T
group by NUMERO_IMMATRICULATION;

select S.ID_PARKING, NOM_PARKING, COUNT(*)
from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
group by S.ID_PARKING, NOM_PARKING
order by COUNT(*) desc;

/*we need to add select par COMMUNE*/
select NOM_PARKING, SUM(COUT_STAT) AS "cout de stationnement"
from (select NUMERO_IMMATRICULATION,NOM_PARKING, SUM(P.TARIF * DATEDIFF(HOUR,S.HEURE_STATIONNEMENT_S,S.HEURE_STATIONNEMENT_E) * 24) AS "COUT_STAT" 
        from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING
        group by NUMERO_IMMATRICULATION,NOM_PARKING
        ) AS T
group by NOM_PARKING
order by desc;

select COMMUNE, COUNT(*)
from STATIONNEMENT S inner join PARKING P on P.ID_PARKING = S.ID_PARKING inner join COMMUNE C on C.CODE_POSTALE = P.CODE_POSTALE
where S.DATE_STATIONNEMENT_E between $date1 and $date2
group by COMMUNE
order by COUNT(*) desc;